(function(){'use strict';var uibench={state:{}};uibench.state.TABLE_ALPHABET_LENGTH=10;uibench.state.TABLE_ALPHABETS=["0123456789","3057846291","8356294107","0861342795"];uibench.state.HomeState=function(){};uibench.state.TableState=function(a,b,d){this.filter=a;this.sort=b;this.items=d};
uibench.state.TableState.create=function(a,b){for(var d=[],c=0;c<a;c++){for(var f=[],e=0;e<b;e++){for(var h="",g=c,k=uibench.state.TABLE_ALPHABETS[e];g>=uibench.state.TABLE_ALPHABET_LENGTH;)h+=k[g%uibench.state.TABLE_ALPHABET_LENGTH],g=g/uibench.state.TABLE_ALPHABET_LENGTH|0;h+=k[g%uibench.state.TABLE_ALPHABET_LENGTH];f.push(h)}d.push(uibench.state.TableItemState.create(!1,f))}return new uibench.state.TableState(null,null,d)};
uibench.state.TableItemState=function(a,b,d){this.id=a;this.active=b;this.props=d};uibench.state.TableItemState.create=function(a,b){return new uibench.state.TableItemState(uibench.state.TableItemState._nextId++,a,b)};uibench.state.TableItemState._nextId=0;uibench.state.AnimState=function(a){this.items=a};uibench.state.AnimState.create=function(a){for(var b=[],d=0;d<a;d++)b.push(uibench.state.AnimBoxState.create(0));return new uibench.state.AnimState(b)};
uibench.state.AnimBoxState=function(a,b){this.id=a;this.time=b};uibench.state.AnimBoxState.create=function(a){return new uibench.state.AnimBoxState(uibench.state.AnimBoxState._nextId++,a)};uibench.state.AnimBoxState._nextId=0;uibench.state.TreeState=function(a){this.root=a};
uibench.state.TreeState.create=function(a){function b(d){var c,f=a[d],e=[];if(d===a.length-1)for(c=0;c<f;c++)e.push(uibench.state.TreeNodeState.create(!1,null));else for(c=0;c<f;c++)e.push(uibench.state.TreeNodeState.create(!0,b(d+1)));return e}return new uibench.state.TreeState(uibench.state.TreeNodeState.create(!0,b(0)))};uibench.state.TreeNodeState=function(a,b,d){this.id=a;this.container=b;this.children=d};
uibench.state.TreeNodeState.create=function(a,b){return new uibench.state.TreeNodeState(uibench.state.TreeNodeState._nextId++,a,b)};uibench.state.TreeNodeState._nextId=0;uibench.state.AppState=function(a,b,d,c,f){this.location=a;this.home=b;this.table=d;this.anim=c;this.tree=f};uibench.actions={};uibench.actions.switchTo=function(a,b){return a.location===b?a:new uibench.state.AppState(b,a.home,a.table,a.anim,a.tree)};uibench.actions.tableFilterBy=function(a,b){return new uibench.state.AppState(a.location,a.home,new uibench.state.TableState(b,a.table.sort,a.table.items),a.anim,a.tree)};uibench.actions.tableSortBy=function(a,b){return new uibench.state.AppState(a.location,a.home,new uibench.state.TableState(a.table.filter,b,a.table.items),a.anim,a.tree)};
uibench.actions.tableActivateEach=function(a,b){for(var d=a.table.items,c=[],f=0;f<d.length;f++)0==f%b?c.push(new uibench.state.TableItemState(d[f].id,!0,d[f].props)):c.push(d[f]);return new uibench.state.AppState(a.location,a.home,new uibench.state.TableState(a.table.filter,a.table.sort,c),a.anim,a.tree)};
uibench.actions.animAdvanceEach=function(a,b){for(var d=a.anim.items,c=[],f=0;f<d.length;f++)0==f%b?c.push(new uibench.state.AnimBoxState(d[f].id,d[f].time+1)):c.push(d[f]);return new uibench.state.AppState(a.location,a.home,a.table,new uibench.state.AnimState(c),a.tree)};uibench.actions.treeCreate=function(a,b){return new uibench.state.AppState(a.location,a.home,a.table,a.anim,uibench.state.TreeState.create(b))};
uibench.actions.treeTransform=function(a,b){function d(a,f){var e=(0,b[f])(a.children);if(f<b.length-1)for(var h=0;h<e.length;h++)e[h]=d(e[h],f+1);return new uibench.state.TreeNodeState(a.id,a.container,e)}return new uibench.state.AppState(a.location,a.home,a.table,a.anim,new uibench.state.TreeState(d(a.tree.root,0)))};uibench.Group=function(a,b,d){this.name=a;this.from=b;this.to=d};uibench.Executor=function(a,b,d,c){this.iterations=a;this.groups=b;this.onUpdate=d;this.onFinish=c;this._samples={};this._currentGroup=0;this._currentGroupState=-1;this._currentIteration=0;this._iter=this._iter.bind(this)};
uibench.Executor.prototype._iter=function(){if(-1===this._currentGroupState)this.onUpdate(this.groups[this._currentGroup].from),this._currentGroupState++,setTimeout(this._iter,0);else if(this._currentGroupState<this.groups[this._currentGroup].to.length){var a=this.groups[this._currentGroup];this.onUpdate(a.from);var b=window.performance.now();this.onUpdate(a.to[this._currentGroupState]);var b=window.performance.now()-b,d=this._samples[a.name];void 0===d&&(d=this._samples[a.name]=[]);d.push(b);this._currentGroupState++;
setTimeout(this._iter,0)}else if(this._currentGroup++,this._currentGroupState=-1,this._currentGroup<this.groups.length)this._iter();else if(this._currentIteration<this.iterations-1)this._currentGroup=0,this._currentIteration++,this._iter();else this.onFinish(this._samples)};uibench.Executor.prototype.run=function(){this._iter()};uibench.tree_transformers={};uibench.tree_transformers.skip=function(a){return a.slice()};uibench.tree_transformers.reverse=function(a){a=a.slice();a.reverse();return a};uibench.tree_transformers.insertFirst=function(a){return function(b){b=b.slice();for(var d=0;d<a;d++)b.unshift(uibench.state.TreeNodeState.create(!1,null));return b}};uibench.tree_transformers.insertLast=function(a){return function(b){b=b.slice();for(var d=0;d<a;d++)b.push(uibench.state.TreeNodeState.create(!1,null));return b}};
uibench.tree_transformers.removeFirst=function(a){return function(b){b=b.slice();for(var d=0;d<a;d++)b.shift();return b}};uibench.tree_transformers.removeLast=function(a){return function(b){b=b.slice();for(var d=0;d<a;d++)b.pop();return b}};uibench.tree_transformers.moveFromEndToStart=function(a){return function(b){b=b.slice();for(var d=0;d<a;d++)b.unshift(b.pop());return b}};
uibench.tree_transformers.moveFromStartToEnd=function(a){return function(b){b=b.slice();for(var d=0;d<a;d++)b.push(b.shift());return b}};uibench.TABLE_ROWS=100;uibench.TABLE_COLS=4;uibench.ANIM_COUNT=100;uibench.tests=null;uibench.iterations=3;uibench.name="unnamed";uibench.version="0.0.0";uibench.report=!1;
uibench.init=function(a,b){function d(a,b,c){for(var d=[],e=0;e<c;e++)a=uibench.actions.animAdvanceEach(a,b),d.push(a);return d}function c(a,b){for(var c=[];0<b;)c.push(a),b--;return c}uibench.name=a;uibench.version=b;var f=function(a){if(0===a.length)return{};for(var b={},c=0;c<a.length;++c){var d=a[c].split("=",2);b[d[0]]=1==d.length?"":decodeURIComponent(d[1].replace(/\+/g," "))}return b}(window.location.search.substr(1).split("&"));void 0!==f.i&&(uibench.iterations=parseInt(f.i,10));void 0!==
f.name&&(uibench.name=f.name);void 0!==f.version&&(uibench.version=f.version);void 0!==f.report&&(uibench.report=!0);var f=new uibench.state.AppState("home",new uibench.state.HomeState,uibench.state.TableState.create(uibench.TABLE_ROWS,uibench.TABLE_COLS),uibench.state.AnimState.create(uibench.ANIM_COUNT),uibench.state.TreeState.create([0])),e=uibench.actions.switchTo(f,"table"),h=uibench.actions.switchTo(f,"anim"),g=uibench.actions.switchTo(f,"tree"),k=uibench.actions.treeCreate(g,[500]),l=uibench.actions.treeCreate(g,
[50,10]),m=uibench.actions.treeCreate(g,[10,50]),g=uibench.actions.treeCreate(g,[5,100]);uibench.tests=[new uibench.Group("table/render",f,c(e,5)),new uibench.Group("table/sort/0",e,c(uibench.actions.tableSortBy(e,0),5)),new uibench.Group("table/sort/1",e,c(uibench.actions.tableSortBy(e,1),5)),new uibench.Group("table/sort/2",e,c(uibench.actions.tableSortBy(e,2),5)),new uibench.Group("table/sort/3",e,c(uibench.actions.tableSortBy(e,3),5)),new uibench.Group("table/filter/32",e,c(uibench.actions.tableFilterBy(e,
32),5)),new uibench.Group("table/filter/16",e,c(uibench.actions.tableFilterBy(e,16),5)),new uibench.Group("table/filter/8",e,c(uibench.actions.tableFilterBy(e,8),5)),new uibench.Group("table/filter/4",e,c(uibench.actions.tableFilterBy(e,4),5)),new uibench.Group("table/filter/2",e,c(uibench.actions.tableFilterBy(e,2),5)),new uibench.Group("table/activate/32",e,c(uibench.actions.tableActivateEach(e,32),5)),new uibench.Group("table/activate/16",e,c(uibench.actions.tableActivateEach(e,16),5)),new uibench.Group("table/activate/8",
e,c(uibench.actions.tableActivateEach(e,8),5)),new uibench.Group("table/activate/4",e,c(uibench.actions.tableActivateEach(e,4),5)),new uibench.Group("table/activate/2",e,c(uibench.actions.tableActivateEach(e,2),5)),new uibench.Group("table/activate/1",e,c(uibench.actions.tableActivateEach(e,1),5)),new uibench.Group("anim/32",h,d(h,32,5)),new uibench.Group("anim/16",h,d(h,16,5)),new uibench.Group("anim/8",h,d(h,8,5)),new uibench.Group("anim/4",h,d(h,4,5)),new uibench.Group("anim/2",h,d(h,2,5)),new uibench.Group("anim/1",
h,d(h,1,5)),new uibench.Group("tree/render/[500]",f,c(k,5)),new uibench.Group("tree/render/[50, 10]",f,c(l,5)),new uibench.Group("tree/render/[10, 50]",f,c(m,5)),new uibench.Group("tree/render/[5, 100]",f,c(g,5)),new uibench.Group("tree/update/[500]/[reverse]",k,c(uibench.actions.treeTransform(k,[uibench.tree_transformers.reverse]),5)),new uibench.Group("tree/update/[50, 10]/[reverse]",l,c(uibench.actions.treeTransform(l,[uibench.tree_transformers.reverse]),5)),new uibench.Group("tree/update/[10, 50]/[reverse]",
m,c(uibench.actions.treeTransform(m,[uibench.tree_transformers.reverse]),5)),new uibench.Group("tree/update/[5, 100]/[reverse]",g,c(uibench.actions.treeTransform(g,[uibench.tree_transformers.reverse]),5)),new uibench.Group("tree/update/[500]/[insertFirst(1)]",k,c(uibench.actions.treeTransform(k,[uibench.tree_transformers.insertFirst(1)]),5)),new uibench.Group("tree/update/[50, 10]/[insertFirst(1)]",l,c(uibench.actions.treeTransform(l,[uibench.tree_transformers.insertFirst(1)]),5)),new uibench.Group("tree/update/[10, 50]/[insertFirst(1)]",
m,c(uibench.actions.treeTransform(m,[uibench.tree_transformers.insertFirst(1)]),5)),new uibench.Group("tree/update/[5, 100]/[insertFirst(1)]",g,c(uibench.actions.treeTransform(g,[uibench.tree_transformers.insertFirst(1)]),5)),new uibench.Group("tree/update/[500]/[insertLast(1)]",k,c(uibench.actions.treeTransform(k,[uibench.tree_transformers.insertLast(1)]),5)),new uibench.Group("tree/update/[50, 10]/[insertLast(1)]",l,c(uibench.actions.treeTransform(l,[uibench.tree_transformers.insertLast(1)]),5)),
new uibench.Group("tree/update/[10, 50]/[insertLast(1)]",m,c(uibench.actions.treeTransform(m,[uibench.tree_transformers.insertLast(1)]),5)),new uibench.Group("tree/update/[5, 100]/[insertLast(1)]",g,c(uibench.actions.treeTransform(g,[uibench.tree_transformers.insertLast(1)]),5)),new uibench.Group("tree/update/[500]/[removeFirst(1)]",k,c(uibench.actions.treeTransform(k,[uibench.tree_transformers.removeFirst(1)]),5)),new uibench.Group("tree/update/[50, 10]/[removeFirst(1)]",l,c(uibench.actions.treeTransform(l,
[uibench.tree_transformers.removeFirst(1)]),5)),new uibench.Group("tree/update/[10, 50]/[removeFirst(1)]",m,c(uibench.actions.treeTransform(m,[uibench.tree_transformers.removeFirst(1)]),5)),new uibench.Group("tree/update/[5, 100]/[removeFirst(1)]",g,c(uibench.actions.treeTransform(g,[uibench.tree_transformers.removeFirst(1)]),5)),new uibench.Group("tree/update/[500]/[removeLast(1)]",k,c(uibench.actions.treeTransform(k,[uibench.tree_transformers.removeLast(1)]),5)),new uibench.Group("tree/update/[50, 10]/[removeLast(1)]",
l,c(uibench.actions.treeTransform(l,[uibench.tree_transformers.removeLast(1)]),5)),new uibench.Group("tree/update/[10, 50]/[removeLast(1)]",m,c(uibench.actions.treeTransform(m,[uibench.tree_transformers.removeLast(1)]),5)),new uibench.Group("tree/update/[5, 100]/[removeLast(1)]",g,c(uibench.actions.treeTransform(g,[uibench.tree_transformers.removeLast(1)]),5)),new uibench.Group("tree/update/[500]/[moveFromEndToStart(1)]",k,c(uibench.actions.treeTransform(k,[uibench.tree_transformers.moveFromEndToStart(1)]),
5)),new uibench.Group("tree/update/[50, 10]/[moveFromEndToStart(1)]",l,c(uibench.actions.treeTransform(l,[uibench.tree_transformers.moveFromEndToStart(1)]),5)),new uibench.Group("tree/update/[10, 50]/[moveFromEndToStart(1)]",m,c(uibench.actions.treeTransform(m,[uibench.tree_transformers.moveFromEndToStart(1)]),5)),new uibench.Group("tree/update/[5, 100]/[moveFromEndToStart(1)]",g,c(uibench.actions.treeTransform(g,[uibench.tree_transformers.moveFromEndToStart(1)]),5)),new uibench.Group("tree/update/[500]/[moveFromStartToEnd(1)]",
k,c(uibench.actions.treeTransform(k,[uibench.tree_transformers.moveFromStartToEnd(1)]),5)),new uibench.Group("tree/update/[50, 10]/[moveFromStartToEnd(1)]",l,c(uibench.actions.treeTransform(l,[uibench.tree_transformers.moveFromStartToEnd(1)]),5)),new uibench.Group("tree/update/[10, 50]/[moveFromStartToEnd(1)]",m,c(uibench.actions.treeTransform(m,[uibench.tree_transformers.moveFromStartToEnd(1)]),5)),new uibench.Group("tree/update/[5, 100]/[moveFromStartToEnd(1)]",g,c(uibench.actions.treeTransform(g,
[uibench.tree_transformers.moveFromStartToEnd(1)]),5))]};"undefined"===typeof window.performance&&(window.performance={});if(!window.performance.now){var nowOffset=Date.now();window.performance.timing&&window.performance.timing.navigationStart&&(nowOffset=window.performance.timing.navigationStart);window.performance.now=function(){return Date.now()-nowOffset}};uibench.run=function(a,b){(new uibench.Executor(uibench.iterations,uibench.tests,a,function(a){b(a);uibench.report&&window.opener.postMessage({type:"report",data:{name:uibench.name,version:uibench.version,samples:a}},"*")})).run()};uibench.export={};window.uibench={init:uibench.init,run:uibench.run};}).call();
